#!/usr/bin/env node
/** Exact resumable jobs. A generated file alone never means QA passed. */
import fs from 'node:fs'
import crypto from 'node:crypto'
const read=f=>JSON.parse(fs.readFileSync(f,'utf8'))
const base='src/data/catalog/'
const products=read(base+'products.json'), couples=read(base+'couples.json')
const byId=new Map(products.map(p=>[p.id,p]))
const old=fs.existsSync(base+'generation-queue.json')?read(base+'generation-queue.json'):{jobs:[]}
const existing=new Map(old.jobs.map(j=>[j.id,j]))
const worlds=['Garba','Navratri','College Fest','Diwali','Festive Party']
const scenes={Garba:'a colourful Gujarati Garba ground at night, canopy textiles and string lights, no identifiable extra people',Navratri:'a decorated Navratri courtyard at night with colourful lanterns and dandiya decorations, no identifiable extra people','College Fest':'an Indian college campus cultural fest, decorated corridor, handmade festival bunting, no identifiable extra people',Diwali:'an Indian home terrace on Diwali evening with diyas at a safe distance and warm lights','Festive Party':'a contemporary Indian festive venue, intimate warm lights, textured walls, informal celebration, no wedding decor'}
const dancePoses=['one partner raises their joined hands as the woman begins a gentle twirl, man watches her, both feet grounded','walking hand in hand, woman half a step ahead looking back at the man','dandiya interaction, one short stick in each outer hand, sticks meet at shoulder height, other hands relaxed','walking away from camera side by side, both turn their heads slightly toward each other','laughing together after dancing, relaxed shoulders and different weight on each leg','woman takes a small dance step as man mirrors her sideways, loose natural arm gestures','man holds the end of his own printed stole while she gestures toward the dance circle','side by side with her hand resting lightly on his upper arm, both watching lights off camera','woman shows her bangles, man smiles down at the details','one partner gently leads the other by the hand through the lights','woman swirls one edge of her skirt while the man applauds with hands separated','seated on a low decorated courtyard bench, leaning toward one another and talking','relaxed side embrace, his forearm rests over her far shoulder, she smiles at him','one partner adjusts the loose end of the other’s stole at shoulder level','both look down at their shoes mid-step, laughing, hands free','standing diagonally facing each other, candid conversation and subtle smiles','woman faces the camera naturally, man looks at her while standing a step behind','back-view walking along a lantern path, silhouettes and outfit details clearly visible','woman lifts her dupatta clear of the floor, man waits beside her with relaxed posture','relaxed mirror selfie in the festival venue entrance, man holds a phone in one hand, woman stands at a slight angle beside him']
const socialPoses=['walking hand in hand, woman a half-step ahead, looking back and smiling','seated candid on a low bench, man leans forward laughing while woman turns toward him','standing close in candid conversation, hands relaxed and separate','a relaxed mirror selfie near the venue entrance, woman holds a phone with one hand','walking away from camera with joined hands, heads gently turned toward one another','man takes a casual photo of the woman with his phone, both people visible in the frame','woman adjusts the cuff of his sleeve while he smiles','laughing together, one hand resting lightly on the other’s shoulder','side by side looking at lights, three-quarter back view','one partner leads the other through the courtyard by the hand','she lightly twirls, he watches from half a step away with a spontaneous smile','sitting on adjacent steps, shoulders close, looking at each other','arm around shoulder, relaxed and playful rather than romantic studio posing','woman faces the camera, man looks at her, natural stance','walking through warm lights, both looking forward, hands separate','one partner playfully reaches for the other’s hand as they turn','standing diagonally near a textured wall, talking, no symmetrical stance','seated on a terrace bench, looking toward the evening skyline together','woman tucks her dupatta over her own shoulder, man waits beside her','man adjusts his own collar while woman smiles toward camera']
const cameras=['35mm eye-level full body, generous headroom, both feet visible','50mm slightly low full body, diagonally framed with both feet visible','35mm off-centre environmental full body','50mm three-quarter angle full body with outfit hems visible','35mm documentary full body, gentle motion in textile only']
const detail=p=>`${p.title}; ${p.gender}; category ${p.category}; subcategory ${p.subCategory}; silhouette ${p.silhouette}; ${p.colour} with ${p.secondaryColour||'tonal'} accents; ${p.fabric} textile appearance; ${p.pattern||'no all-over print'}; ${p.embroidery||p.weave||'no heavy embroidery'}`
function build(job){
 const previous=existing.get(job.id), promptHash=crypto.createHash('sha256').update(job.prompt).digest('hex')
 return {...job,promptHash,status:previous?.promptHash===promptHash?previous.status:'queued',attempts:previous?.attempts||[],referenceGate:'blocked-contact-sheets-unavailable',qa:previous?.promptHash===promptHash?previous.qa:{metadata:false,anatomy:false,age:job.kind==='product'?null:false,referenceMatch:false,unique:false}}
}
const jobs=[]
for(const p of products){
 const world=worlds.find(w=>p.occasions.includes(w)),accessory=!p.inHouseTryOn
 const priority=accessory?9:world==='Garba'||world==='Navratri'?1:world==='College Fest'?3:world==='Diwali'?5:7
 const scene=scenes[world]
 const prompt=`Original premium Indian fashion editorial, single ${accessory?'product still-life, no people, show the actual accessory or beauty object only':'full-body faceless identity-neutral fashion model'}. ${detail(p)}. ${p.category==='chaniya-choli'?'Fitted choli, full circular flared chaniya, embroidered skirt border and colourful odhani; oxidised silver jhumkas and a few bangles. ':''}${p.gender==='men'&&p.inHouseTryOn?'Young contemporary relaxed fit, not groomwear; ivory straight bottoms, simple juttis, selective colourful Gujarati embroidery, no ceremonial costume. ':''}For ${world}. ${scene}. Realistic textile texture and natural drape, accurate construction and colour, soft cinematic light, ${accessory?'entire object visible':'entire garment and footwear visible'}, portrait 3:4. Original composition with varied architectural setting. No text, watermark, logo, branding, extra limbs, malformed hands, plastic fabric, floating clothes, duplicated accessories or cropped hems. No photograph reuse or recolour of an existing image.`
 p.imagePrompt=prompt
 jobs.push(build({id:p.id,kind:'product',priority,world,target:`public/images/original-products/${p.id}.jpg`,prompt,dimensions:'3:4'}))
}
for(const [wi,world] of worlds.entries()) couples.filter(c=>c.world===world).forEach((c,i)=>{
 const her=byId.get(c.herProductIds[0]),his=byId.get(c.hisProductIds[0]),pose=(wi<2?dancePoses:socialPoses)[(i+wi*3)%20],camera=cameras[(i+wi)%cameras.length]
 const prompt=`Original candid Indian fashion editorial photograph, portrait 3:4. Exactly two real-looking young adult Indian people, one woman and one man aged 20 to 24, clearly college/festival age, realistic skin texture, youthful natural faces, realistic hair, imperfect spontaneous smiles. Her exact outfit: ${detail(her)}. His exact outfit: ${detail(his)}. ${her.category==='chaniya-choli'?'Her outfit has a fitted embroidered choli, full flared dance-friendly chaniya skirt with Kutchi-inspired border, colourful odhani, small oxidised silver earrings and bangles. ':''}He wears ivory straight bottoms and simple festive juttis, relaxed contemporary Indian styling, no royal or groom costume. Pose geometry: ${pose}. Camera: ${camera}. Environment: ${scenes[world]}. Natural fabric behaviour, believable body proportions, tasteful young couple chemistry, organic Pinterest/Instagram photography rather than glossy perfume-ad poses. Entire outfits and both people visible, do not crop away either partner. An original composition, no reproduction of third-party photos or faces. Avoid mannequin, faceless people, plastic skin, mature married-couple look, bride, groom, wedding staging, stiff stock portrait, identical outfits, excessive gold, distorted anatomy, extra fingers or limbs, text, watermarks and logos.`
 c.imagePrompt=prompt
 jobs.push(build({id:c.id,kind:'couple',priority:wi<2?2:wi===2?4:wi===3?6:8,world,calibration:i<2,target:`public/images/original-couples/${c.id}.jpg`,prompt,pose,camera,environment:scenes[world],dimensions:'3:4'}))
})
jobs.sort((a,b)=>a.priority-b.priority||a.id.localeCompare(b.id))
for(const [name,data] of [['products',products],['couples',couples],['generation-queue',{version:1,referenceStatus:'BLOCKED: no contact sheets were attached; supplied Pinterest URLs returned 403',calibrationGate:'pending-review',jobs}]]) {fs.writeFileSync(base+name+'.json.tmp',JSON.stringify(data,null,1)+'\n');fs.renameSync(base+name+'.json.tmp',base+name+'.json')}
console.log(`${jobs.length} resumable jobs, ${jobs.filter(j=>j.calibration).length} calibration candidates; no implicit approvals`)
