import fs from 'node:fs'
import {evidence,checkedAt} from './price-evidence.mjs'
const products=JSON.parse(fs.readFileSync('src/data/catalog/products.json','utf8'))
let text=`# Marketplace price research\n\nChecked: ${checkedAt} (UTC). Sources were accessible web search extracts, not checkout verification. Search-index prices may be stale, region-specific or conditional. No item is promoted to LIVE.\n\n## Method\n\nThe catalog is original editorial styling, NOT an exact-SKU feed. Unverified legacy brand claims and synthetic MRPs were removed. Exact marketplace brands below identify only the observed comparator. Products carry CHECK, a price basis and evidence ID. A merchant search URL is a discovery fallback, not proof of an identical purchasable garment.\n\nEstimates use the documented family range: simple/printed construction at the lower end, threadwork in the middle, mirror/bead embellishment at the upper end. A heavy handwork or pure-silk claim is not substantiated by a basic machine-embroidered comparator. There is no fabricated discount or commission.\n\n| Evidence ID / search term | Merchant | Observed result | Observed range | Estimated price anchors | Mapped records |\n|---|---|---|---|---|---|\n`
let i=0
for(const [id,e] of Object.entries(evidence)){i++;text+=`| ${id}: ${e.query} | ${e.merchant} [${i}](${e.url}) | ${e.observed} | ₹${e.range.join('–₹')} | ₹${[...new Set(e.prices)].join(', ₹')} | ${products.filter(p=>p.priceEvidenceId===id).length} |\n`}
const pending=products.filter(p=>p.priceBasis!=='market-comparable-estimate')
text+=`\n## Coverage and limitations\n\n- Family-comparable estimates: **${products.length-pending.length}/653**. Not exact SKU matches.\n- **${pending.length}/653 still require appropriate product-family evidence** (including embroidered ethnic shirts and accessories/beauty families). Their inherited prices remain explicitly unverified; no false mapping to an unrelated comparator.\n- Approved sources consulted: Myntra, AJIO, Flipkart, Meesho, Nykaa; targeted Shopsy searches returned unrelated sites and were excluded.\n- Nykaa is restricted to beauty in the catalog. Kajal research showed ₹129–₹595, but this does not price all cosmetics, fragrance or skincare. [10](https://www.nykaa.com/makeup/eyes/kajal/c/687)\n- Meesho adult jutti listings showed examples ₹314–₹1,564, some conditional on first-order offers; these do not substantiate all shoes. [11](https://meesho.com/hi/jutti/pl/ybkys)\n- Rubans oxidised jhumka with hair chains was observed at ₹654, not a universal jewellery price. [12](https://www.myntra.com/earrings/rubans/rubans-oxidised-silver-plated-ghumroo-beaded-dome-jhumka-with-triple-layer-hair-chain/25417260/buy)\n\n**Pricing acceptance is not complete.** Remaining IDs and prices are recorded in \`docs/audits/price-mapping.json\`.\n`
fs.mkdirSync('docs/audits',{recursive:true});fs.writeFileSync('docs/price-research.md',text)
fs.writeFileSync('docs/audits/price-mapping.json',JSON.stringify(products.map(p=>({id:p.id,category:p.category,price:p.price,basis:p.priceBasis,evidenceId:p.priceEvidenceId,lastChecked:p.lastChecked})),null,2)+'\n')
console.log(`${products.length-pending.length}/653 family estimates; ${pending.length} unverified prices remain`)
